### ISSUE TITLE
Would you consider a dual license?

### ISSUE THREAD

**Issue by technosophos** [amandasaurus/rust-cgi#17]
I admit that it is very presumptuous to ever ask someone to do this, but would you consider offering a license that is not a GPLv3 or AGPL derivative? My company allows us to use almost all open source licenses, but GPLv3 and AGPL are both disallowed. GPLv2, LGPL, Apache, MIT, BSD, MPL.... all of the other common ones are okay.

If you don't feel comfortable changing licenses, I totally understand and respect that. I just thought I would ask.

We've been using it in our experimentation with Wagi (https://github.com/deislabs/wagi), which compiles Rust to Wasm32-WASI, and then executes it in a CGI/1.1-like way. I wrote a tutorial for using your CGI library with Wagi: https://github.com/technosophos/codewalk-wagi. So it's really a perfect fit for what we are doing--and we'll continue to point our users to it regardless of your license. (We just won't be able to use it ourselves)

**Comment by amandasaurus** [comment]
> My company allows us to use almost all open source licenses, but GPLv3 and AGPL are both disallowed

Why is that? Is there something wrong with the AGPL? Have I chosen the wrong licence?

**Comment by amandasaurus** [comment]
I suppose I could look at dual licencing to something not derived from that, like https://ethicalsource.dev/

**Comment by amandasaurus** [comment]
Wait, "your company" is Microsoft? Now I understand.

I'm sorry you don't like the `cgi` code I wrote, if you don't like it, I'm prepared to offer you a full refund.

**Comment by technosophos** [comment]
Sorry... not sure I understand that last message. I _love_ the CGI module, and would really like to use it. It's been great to work with. I work in an open source lab at MS. MS lawyers have issues with AGPLv3 and GPLv3, though (since I'm not a lawyer) I am not sure what they are. I'm just trying to comply with our requirements.

I am hoping to use the CGI library for some of our Wagi stuff because it is such a perfect fit. We've been doing all of this WebAssembly work with CNCF and the Bytecode Alliance, and using the CGI protocol has made it possible for us to build web apps while the working groups still figure out how to implement networking in Wasm.

Anyway, sorry you felt offended. Today I'll fix up the license on my codewalk. Thanks for pointing that out.
